---
title: "Qu(h)ackthon 2018 - Proposal"
author: "Rob Fowler"
date: "2018-06-14"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Topic: Extract Data from Photos
Create an interface for users to annotate pictures from photo surveys to distill higher level data about bird count (possibly species).

- When:  Saturday 11 August 2018  ??am - ??pm
  - Code for America: [National Day of Civic Hacking](https://www.codeforamerica.org/events/national-day-of-civic-hacking)
- Where: ???
- Who: Anybody and Everybody 


## Main Pieces

1. Photo Management (Pre-annotation) 
2. Annotation Tool
3. Creation of analyzable data

## Pre-Annotation

1. **Photo Management** (Pre-annotation) 
    - Photo file management 
    - Database with meta/covariates for pictures
    - Sampling frame
      - Tiling?
      - Repetition?
      - Randomization?
    - Spooling process to the _Annotation Tool_
2. Annotation Tool
3. Creation of Analyzable Data

## Annotaiton Tool

1. _Photo Management_ 
2. **Annotation Tool**
    - User Interface (UI)
    - Annotation Mechanism (UI)
    - Usability (UX)
    - Documentation 
    - Export to _database_
3. Creation of Analyzable Data

## Distilled Data

1. _Photo Management_ 
2. _Annotation Tool_
3. **Creation of Analyzable Data**
    - Table(s) compatible with database holding photo info
    - Multiple reader comparison tool
    - Relate annotation back to original file (i.e. not just the tile)
    - Update and inform _spooling process_ from before

## Conclusion

- Lots of pieces, but all seem manageable.
- There are non-coding tasks.
- Technical Skills Needed:
    - Database: Postgres / SQL
    - Interface:  Java or Python / Interface Design / Documentation
    - Data product: above database skills / Python or R

